version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped
  app:
    container_name: app
    build: .
    env_file:
      - .env
    ports:
      - "${SRV_PORT}:${SRV_PORT}"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pg-data: